version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=Gkh747c
    volumes:
    - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/invest
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
      - web


