version: "3"

services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/invest
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
      - web


